ADM:
    input_dir: C:\Users\thanakit\Downloads\RAW\ADM
    output_dir: C:\Users\thanakit\Downloads\EXPORT\ADM
    file: ADM.txt
    require: ["BOS"]
BOS:
    input_dir: C:\Users\thanakit\Downloads\RAW\BOS
    output_dir: C:\Users\thanakit\Downloads\EXPORT\BOS
    file: BOS.xlsx
    require: []
CUM:
    input_dir: C:\Users\thanakit\Downloads\RAW\CUM
    output_dir: C:\Users\thanakit\Downloads\EXPORT\CUM
    file: CUM.xls
    require: []
DOC:
    input_dir: C:\Users\thanakit\Downloads\RAW\DOC
    output_dir: C:\Users\thanakit\Downloads\EXPORT\DOC
    file: DocImage.txt
    require: []
ICAS:
    input_dir: C:\Users\thanakit\Downloads\RAW\ICAS
    output_dir: C:\Users\thanakit\Downloads\EXPORT\ICAS
    file: ICAS-NCR.xlsx
    require: []
IIC:
    input_dir: C:\Users\thanakit\Downloads\RAW\IIC
    output_dir: C:\Users\thanakit\Downloads\EXPORT\IIC
    file: IIC.xlsx
    require: []
LDS:
    input_dir: C:\Users\thanakit\Downloads\RAW\LDS
    output_dir: C:\Users\thanakit\Downloads\EXPORT\LDS
    file: LDS-P_UserDetail.txt
    require: []
LEAD:
    input_dir: C:\Users\thanakit\Downloads\RAW\LEAD
    output_dir: C:\Users\thanakit\Downloads\EXPORT\LEAD
    file: Lead-Management.xlsx
    require: []
MOC:
    input_dir: C:\Users\thanakit\Downloads\RAW\MOC
    output_dir: C:\Users\thanakit\Downloads\EXPORT\MOC
    file: MOC.xlsx
    require: []