ADM:
    input_dir: C:\Users\thanakit\Downloads\RAW\ADM
    output_dir: C:\Users\thanakit\Downloads\EXPORT\ADM
    file: ADM.txt
    require: ["BOS"]
BOS:
    input_dir: C:\Users\thanakit\Downloads\RAW\BOS
    output_dir: C:\Users\thanakit\Downloads\EXPORT\BOS
    file: BOS.xlsx
    require: []
CUM:
    input_dir: C:\Users\thanakit\Downloads\RAW\CUM
    output_dir: C:\Users\thanakit\Downloads\EXPORT\CUM
    file: CUM.xls
    require: []
DOC:
    input_dir: C:\Users\thanakit\Downloads\RAW\DOC
    output_dir: C:\Users\thanakit\Downloads\EXPORT\DOC
    file: DocImage.txt
    require: []
ICAS:
    input_dir: C:\Users\thanakit\Downloads\RAW\ICAS
    output_dir: C:\Users\thanakit\Downloads\EXPORT\ICAS
    file: ICAS-NCR.xlsx
    require: []

# IIC:
#     curr: 5
#     volt: 5
# LDS:
#     curr: 5
#     volt: 5
# LEAD:
#     curr: 5
#     volt: 5
# MOC:
#     curr: 5
#     volt: 5