config:
    ADM:
        dir_input: C:\Users\thanakit\Downloads\RAW\ADM
        dir_output: C:\Users\thanakit\Downloads\EXPORT\ADM
        file: ADM.txt
        depend_on: [DOC]
    BOS:
        dir_input: C:\Users\thanakit\Downloads\RAW\BOS
        dir_output: C:\Users\thanakit\Downloads\EXPORT\BOS
        file: BOS.xlsx
        depend_on: []
    CUM:
        dir_input: C:\Users\thanakit\Downloads\RAW\CUM
        dir_output: C:\Users\thanakit\Downloads\EXPORT\CUM
        file: CUM.xls
        depend_on: []
    DOC:
        dir_input: C:\Users\thanakit\Downloads\RAW\DOC
        dir_output: C:\Users\thanakit\Downloads\EXPORT\DOC
        file: DocImage.txt
        depend_on: [ADM, BOS]
    ICAS:
        dir_input: C:\Users\thanakit\Downloads\RAW\ICAS
        dir_output: C:\Users\thanakit\Downloads\EXPORT\ICAS
        file: ICAS-NCR.xlsx
        depend_on: [CUM]

# IIC:
#     curr: 5
#     volt: 5
# LDS:
#     curr: 5
#     volt: 5
# LEAD:
#     curr: 5
#     volt: 5
# MOC:
#     curr: 5
#     volt: 5