version: 1
disable_existing_loggers: false,
formatters: 
  verbose: 
    class: logging.Formatter
    format: "%(asctime)s.%(msecs)03d | %(processName)s | %(levelname)s | convert_2_files | %(module)s | %(funcName)s::%(lineno)d | message >> %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: verbose
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    backupCount: 0
    mode: w
    filename: ./log/
root: 
  level: INFO
  handlers:
    - console
    # - file
