ADM:
    input_dir: D:\IGAGD\ADM\download
    output_dir: D:\IGAGD\ADM\upload
    input_file: ADM.txt
    output_file: ADMIGAWINT.csv
    require: []
BOS:
    input_dir: D:\IGAGD\BOS\download
    output_dir: D:\IGAGD\BOS\upload
    input_file: BOS.xlsx
    output_file: BOSIGAWINT.csv
    require: []
CUM:
    input_dir: D:\IGAGD\CUM\download
    output_dir: D:\IGAGD\CUM\upload
    input_file: CUM.xls
    output_file: CUMIGAWINT.csv
    require: []
DOC:
    input_dir: D:\IGAGD\DOC\download
    output_dir: D:\IGAGD\DOC\upload
    input_file: DocImage.txt
    output_file: DOC.csv
    require: []
ICA:
    input_dir: D:\IGAGD\ICA\download
    output_dir: D:\IGAGD\ICA\upload
    input_file: ICAS-NCR.xlsx
    output_file: ICAIGAWINT.csv
    require: []
IIC:
    input_dir: D:\IGAGD\IIC\download
    output_dir: D:\IGAGD\IIC\upload
    input_file: IIC.xlsx
    output_file: IICIGAWINT.csv
    require: []
LDS:
    input_dir: D:\IGAGD\LDS\download
    output_dir: D:\IGAGD\LDS\upload
    input_file: LDS-P_UserDetail.txt
    output_file: LDSIGAWINT.csv
    require: []
LMT:
    input_dir: D:\IGAGD\LMT\download
    output_dir: D:\IGAGD\LMT\upload
    input_file: Lead-Management.xlsx
    output_file: LMTIGAWINT.csv
    require: []
MOC:
    input_dir: D:\IGAGD\MOC\download
    output_dir: D:\IGAGD\MOC\upload
    input_file: MOC.xlsx
    output_file: MOCIGAWINT.csv
    require: []