ADM:
  input_dir: D:\IGAGD\ADM\DOWNLOAD
  output_dir: D:\IGAGD\ADM\UPLOAD
  input_file: ADMUSER.csv
  output_file: ADMIGAWINT.csv, ADMPARAMLIST.csv
BOS:
  input_dir: D:\IGAGD\BOS\DOWNLOAD
  output_dir: D:\IGAGD\BOS\UPLOAD
  input_file: BOSTH.csv
  output_file: BOSIGAWINT.csv, BOSPARAMLIST.csv
  depend_file: BOSTH_Param.csv
CUM:
  input_dir: D:\IGAGD\CUM\DOWNLOAD
  output_dir: D:\IGAGD\CUM\UPLOAD
  input_file: CUMUSER.xls
  output_file: CUMIGAWINT.csv, CUMPARAMLIST.csv
DOC:
  input_dir: D:\IGAGD\DOC\DOWNLOAD
  output_dir: D:\IGAGD\DOC\UPLOAD
  input_file: DocImage.txt
  output_file: DOCIGAWINT.csv, DOCPARAMLIST.CSV
DIL:
  input_dir: D:\IGAGD\DIL\DOWNLOAD
  output_dir: D:\IGAGD\DIL\UPLOAD
  input_file: DocImage1.txt
  output_file: DILIGAWINT.csv, DILPARAMLIST.csv
ICA:
  input_dir: D:\IGAGD\ICA\DOWNLOAD
  output_dir: D:\IGAGD\ICA\UPLOAD
  input_file: ICAS_TBL_USER
  output_file: ICAIGAWINT.csv, ICAPARAMLIST.csv
  depend_file: ICAS_TBL_USER_GROUP , ICAS_TBL_USER_BANK_BRANCH, ICAS_TBL_GROUP
IIC:
  input_dir: D:\IGAGD\IIC\DOWNLOAD
  output_dir: D:\IGAGD\IIC\UPLOAD
  input_file: IICUSER.csv, IICPARAM.csv
  output_file: IICIGAWINT.csv, IICPARAMLIST.csv
LDS:
  input_dir: D:\IGAGD\LDS\DOWNLOAD
  output_dir: D:\IGAGD\LDS\UPLOAD
  input_file: UserDetail.txt
  output_file: LDSIGAWINT.csv, LDSPARAMLIST.CSV
LMT:
  input_dir: D:\IGAGD\LMT\DOWNLOAD
  output_dir: D:\IGAGD\LMT\UPLOAD
  input_file: LMTTH.CSV
  output_file: LMTIGAWINT.csv, LMTPARAMLIST.CSV
MOC:
  input_dir: D:\IGAGD\MOC\DOWNLOAD
  output_dir: D:\IGAGD\MOC\UPLOAD
  input_file: MOCUSER.csv, MOCPARAM.csv
  output_file: MOCIGAWINT.csv, MOCPARAMLIST.csv
