ADM:
  input_dir: D:\IGAGD\ADM\DOWNLOAD
  output_dir: D:\IGAGD\ADM\UPLOAD
  input_file: ADMUSER.txt, ADMUSER.txt
  output_file: ADMIGAWINT.csv, ADMPARAMLIST.csv
BOS:
  input_dir: D:\IGAGD\BOS\DOWNLOAD
  output_dir: D:\IGAGD\BOS\UPLOAD
  input_file: BOSUSER.xlsx
  output_file: BOSIGAWINT.csv
CUM:
  input_dir: D:\IGAGD\CUM\DOWNLOAD
  output_dir: D:\IGAGD\CUM\UPLOAD
  input_file: CUMUSER.xls, CUMUSER.xls
  output_file: CUMIGAWINT.csv, CUMPARAMLIST.csv
DOC:
  input_dir: D:\IGAGD\DOC\DOWNLOAD
  output_dir: D:\IGAGD\DOC\UPLOAD
  input_file: DOCUSER.txt, DOCUSER.txt
  output_file: DOCIGAWINT.csv, DOCPARAMLIST.csv
DIL:
  input_dir: D:\IGAGD\DOC\DOWNLOAD
  output_dir: D:\IGAGD\DOC\UPLOAD
  input_file: DOCUSER.txt, DOCUSER.txt
  output_file: DILIGAWINT.csv, DILPARAMLIST.csv
ICA:
  input_dir: D:\IGAGD\ICA\DOWNLOAD
  output_dir: D:\IGAGD\ICA\UPLOAD
  input_file: ICAS-NCR.xlsx
  output_file: ICAIGAWINT.csv
IIC:
  input_dir: D:\IGAGD\IIC\DOWNLOAD
  output_dir: D:\IGAGD\IIC\UPLOAD
  input_file: IICUSER.csv, IICPARAM.csv
  output_file: IICIGAWINT.csv, IICPARAMLIST.csv
LDS:
  input_dir: D:\IGAGD\LDS\DOWNLOAD
  output_dir: D:\IGAGD\LDS\UPLOAD
  input_file: LDSUSER.txt
  output_file: LDSIGAWINT.csv
LMT:
  input_dir: D:\IGAGD\LMT\DOWNLOAD
  output_dir: D:\IGAGD\LMT\UPLOAD
  input_file: LDSUSER.xlsx
  output_file: LMTIGAWINT.csv
MOC:
  input_dir: D:\IGAGD\MOC\DOWNLOAD
  output_dir: D:\IGAGD\MOC\UPLOAD
  input_file: MOCUSER.csv, MOCPARAM.csv
  output_file: MOCIGAWINT.csv, MOCPARAMLIST.csv
