version: 1
disable_existing_loggers: false,
formatters: 
  verbose: 
    class: logging.Formatter
    format: "%(asctime)s.%(msecs)03d | %(module)10s | %(levelname)8s | %(funcName)20s | %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: verbose
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    backupCount: 5
    mode: w
    filename: 
root: 
  level: INFO
  handlers:
    #- console
    - file
